# Generated by Django 3.1.2 on 2020-11-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20201123_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopedidoprod',
            name='solicitudProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.solicitudproducto'),
        ),
    ]
