# Generated by Django 3.1.2 on 2020-11-25 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_ingresopedidoprod_solicitudproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudproducto',
            name='estado',
        ),
        migrations.AlterField(
            model_name='ingresopedidoprod',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
